[package]
name = "bevy_icon_creator"
version = "0.1.0"
edition = "2021"
authors = ["Franklin E. Blanco"]
description = "A plugin to automatically create Icons from entities in bevy"
license = "MIT"
readme = "README.md"

[lib]

[dependencies]
bevy = { version = "0.13.1" }